Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,8 +19,10 @@ jobs:
         mkdir -p ~/.ssh
         echo "${{ secrets.TEST_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
-        ssh-keyscan -H boldstmedia.com  >> ~/.ssh/known_hosts
-        cat ~/.ssh/id_rsa
+        ssh-keyscan -H boldstmedia.com >> ~/.ssh/known_hosts || (echo "Host key addition failed" && exit 1)
+        ls -la ~/.ssh
+        head -n 5 ~/.ssh/id_rsa # Ensure private key structure
+        cat ~/.ssh/known_hosts # Confirm host key added
 
     - name: Git pull on remote server
       run: ssh -i ~/.ssh/id_rsa boldstme@boldstmedia.com  'touch rob.text'
